version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.2.0

executors:
  base:
    docker:
      - image: cimg/node:16.15.0
        user: root

commands:
  install-node-packages:
    description: Install node packages
    steps:
      - restore_cache:
          key: node-cache-v2-{{ checksum "package-lock.json" }}
      - run:
          name: Install node packages
          command: |
            npm install --save-dev --unsafe-perm node-sass
            npm install
      - save_cache:
          paths:
            - ./node_modules
          key: node-cache-v2-{{ checksum "package-lock.json" }}

jobs:
  tests:
    executor: base
    steps:
      - checkout
      - install-node-packages
      - run:
          name: Run linter and unit tests with coverage
          command: npm run quality
  check-for-pr:
    executor: base
    steps:
      - checkout
      - run: |
          if [[ $CIRCLE_PULL_REQUEST ]]; then
            circleci-agent step halt
          fi
      - continuation/continue:
          configuration_path: .circleci/deployment-workflow.yml

workflows:
  main:
    jobs:
      - tests
      - check-for-pr:
          requires:
            - tests
