version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.6

executors:
  base:
    docker:
      - image: cimg/node:18.12.1
        user: root

commands:
  install-node-packages:
    description: Install node packages
    steps:
      - restore_cache:
          key: node-cache-v2-{{ checksum "package-lock.json" }}
      - run:
          name: Install node packages
          command: |
            npm install --save-dev --unsafe-perm node-sass
            npm install
      - save_cache:
          paths:
            - ./node_modules
          key: node-cache-v2-{{ checksum "package-lock.json" }}
  install-node-and-cypress-packages:
    description: Install node packages and Cypress dependencies
    steps:
      - restore_cache:
          key: node-cache-with-cypress-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Cypress dependencies
          command: |
            apt-get update
            apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run:
          name: Install node packages
          command: |
            npm install --save-dev --unsafe-perm node-sass
            npm install
      - save_cache:
          paths:
            - ./node_modules
            - ~/.cache/Cypress
          key: node-cache-with-cypress-v1-{{ checksum "package-lock.json" }}
  build-and-push:
    description: Build and push code to S3 bucket
    parameters:
      client_id:
        type: string
        default: ''
      gtm_id:
        type: string
        default: ''
      bucket_name:
        type: string
        default: ''
      distribution_id:
        type: string
        default: ''
      mode:
        type: string
        default: ''
    steps:
      - run:
          name: Build code
          command: API_KEY="" CLIENT_ID=<< parameters.client_id >> GTM_ID=<< parameters.gtm_id >> npm run build:<<parameters.mode>>
      - aws-cli/setup
      - run:
          name: Sync build artifacts to S3
          command: aws s3 cp --recursive dist "s3://<< parameters.bucket_name >>/"
      - run:
          name: Create invalidation in CloudFront
          command: aws cloudfront create-invalidation --distribution-id << parameters.distribution_id >> --paths '/*'

jobs:
  e2e-tests:
    executor: base
    steps:
      - checkout
      - install-node-and-cypress-packages
      - run:
          name: Run e2e test cases
          command: ./run_e2e_tests.sh $QA_TEST_URL
  qa-deployment:
    executor: base
    steps:
      - checkout
      - install-node-packages
      - build-and-push:
          client_id: $QA_CLIENT_ID
          gtm_id: $QA_GTM_ID
          bucket_name: $QA_BUCKET_NAME
          distribution_id: $QA_DISTRIBUTION_ID
          mode: dev
  prod-deployment:
    executor: base
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.12
          docker_layer_caching: true
      - install-node-packages
      - build-and-push:
          client_id: $PROD_CLIENT_ID
          gtm_id: $PROD_GTM_ID
          bucket_name: $PROD_BUCKET_NAME
          distribution_id: $PROD_DISTRIBUTION_ID
          mode: prod
      - run:
          name: Build and push Docker image to DockerHub
          command: ./docker_push.sh

workflows:
  build-and-deploy:
    jobs:
      - e2e-tests:
          filters:
            branches:
              only: master
      - approve-qa-deployment:
          type: approval
          requires:
            - e2e-tests
      - qa-deployment:
          requires:
            - approve-qa-deployment
      - approve-prod-deployment:
          type: approval
          requires:
            - qa-deployment
      - prod-deployment:
          requires:
            - approve-prod-deployment
